#!/bin/sh
# https://gist.github.com/miminashi/f83a967f8c1a74dcb927aeb90947d766


node_name="syamimomo"
ip_address="172.50.0.1"


printf 'NODE_NAME: %s\n' "${node_name}"
printf 'IP_ADDRESS: %s\n' "${ip_address}"

# tincのインストール
#apt-get update
#apt-get install -y tinc

# 設定用ディレクトリの作成
mkdir /usr/local/etc/tinc/machikado_network
mkdir /usr/local/etc/tinc/machikado_network/hosts


# 自ノードのノード定義の作成
# いまのところ特に設定する内容は無い
sed 's/{NODE_NAME}/'"${node_name}"'/' > /usr/local/etc/tinc/machikado_network/hosts/"${node_name}" <<'EOF'
# {NODE_NAME}
EOF

# tinc.conf の作成
sed -e 's/{NODE_NAME}/'"${node_name}"'/' > /usr/local/etc/tinc/machikado_network/tinc.conf <<'EOF'
Name = {NODE_NAME}
Mode = switch
Device = /dev/net/tun
EOF


# tinc-up スクリプトの作成
# このシェルスクリプトはVPNセッションの開始時に実行される
sed 's/{IP_ADDRESS}/'"${ip_address}"'/' > /usr/local/etc/tinc/machikado_network/tinc-up <<'EOF'
#!/bin/sh
ip link add br0 type bridge
ip link set br0 up
ip link set $INTERFACE up
ip link set dev $INTERFACE master br0
ip link set dev eth1 master br0
ip addr add {IP_ADDRESS}/8 dev br0
echo 1 > /proc/sys/net/ipv4/ip_forward
iptables-restore < /usr/local/etc/tinc/machikado_network/nat.iptables
EOF
chmod +x /usr/local/etc/tinc/machikado_network/tinc-up

# iptables(NAT)の設定ファイルの作成
cat > /usr/local/etc/tinc/machikado_network/nat.iptables <<'EOF'
# Generated by xtables-save v1.8.2 on Thu Jul 15 00:21:02 2021
*filter
:INPUT ACCEPT [46687:11733996]
:FORWARD ACCEPT [1617:74797]
:OUTPUT ACCEPT [295135:228581507]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i br0 -o eth0 -j DROP
COMMIT
# Completed on Thu Jul 15 00:21:02 2021
# Generated by xtables-save v1.8.2 on Thu Jul 15 00:21:02 2021
*nat
:PREROUTING ACCEPT [15990:4356696]
:INPUT ACCEPT [12944:3533125]
:POSTROUTING ACCEPT [410:45315]
:OUTPUT ACCEPT [175:24583]
-A POSTROUTING -o br0 -j MASQUERADE
COMMIT
# Completed on Thu Jul 15 00:21:02 2021
# Generated by xtables-save v1.8.2 on Thu Jul 15 00:21:02 2021
*mangle
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
COMMIT
# Completed on Thu Jul 15 00:21:02 2021
# Generated by xtables-save v1.8.2 on Thu Jul 15 00:21:02 2021
*raw
:PREROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
COMMIT
# Completed on Thu Jul 15 00:21:02 2021
EOF


# tinc-down スクリプトの作成
# このシェルスクリプトはVPNセッションの終了時に実行される
cat > /usr/local/etc/tinc/machikado_network/tinc-down <<'EOF'
#!/bin/sh
ip link set dev $INTERFACE nomaster
ip link set dev $INTERFACE down
ip link set dev eth1 nomaster
ip link set dev br0 down
ip link del dev br0
EOF
chmod +x /usr/local/etc/tinc/machikado_network/tinc-down

# 鍵生成
tinc -n machikado_network generate-ed25519-keys | cat

#systemctl enable tinc@machikado_network.service


cat /usr/local/etc/tinc/machikado_network/hosts/"${node_name}"
