# -*- mode: ruby -*-
# vi: set ft=ruby :

#require 'tmpdir'
#
#tmpdir = Dir.mktmpdir
#p tmpdir
$store = {}

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  config.vm.provider "virtualbox" do |vb|
    vb.customize ['modifyvm', :id, '--natnet1', '172.16.30.0/24']
  end

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "generic/debian11"
  #config.vm.box = ""

  shell_provision = <<-SHELL
      # スクリプトを配置する
      chmod +x /tmp/bin/*
      cp /tmp/bin/* /usr/local/sbin
      chmod +x /tmp/setup_gateway.sh
      # ノードのセットアップをする
      sudo /tmp/setup_gateway.sh %s %s

      # デバッグ用
      sudo apt-get install -y screen
      sudo -u vagrant curl -s https://gist.githubusercontent.com/miminashi/1d7890a1a5e8d5b18e0c1a9c5e4fff2e/raw | sh -s
  SHELL

  # ルートノードの想定のVM
  config.vm.define "fakeroot" do |host|
    host.vm.hostname = "fakeroot"
    host.vm.network "private_network", ip: "192.168.56.254", netmask: "24", virtualbox__intnet: "fake_inet"  # インターネットのかわり
    host.vm.provision "file", source: "./setup_gateway.sh", destination: "/tmp/"
    host.vm.provision "file", source: "./bin", destination: "/tmp/"
    host.vm.provision "shell", inline: shell_provision % [host.vm.hostname, "10.50.0.1"]
  end

  # 各参加者のLANに設置されるまちかどネットワークゲートウェイの想定のVM
  config.vm.define "gateway" do |host|
    host.vm.hostname = "gateway"
    host.vm.network "private_network", ip: "192.168.56.2", netmask: "24", virtualbox__intnet: "fake_inet"  # インターネットのかわり
    #host.vm.network "private_network", ip: "192.168.57.2", netmask: "24"  # LANのかわり
    host.vm.provision "file", source: "./setup_gateway.sh", destination: "/tmp/"
    host.vm.provision "file", source: "./bin", destination: "/tmp/"
    host.vm.provision "shell", inline: shell_provision % [host.vm.hostname, "10.50.0.2"]
  end

=begin
  # LAN側の端末の想定のVM
  config.vm.define "client" do |host|
    host.vm.hostname = "client"
    host.vm.network "private_network", ip: "192.168.57.3", netmask: "24"
  end
=end
end
