# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.customize ['modifyvm', :id, '--natnet1', '192.168.4.0/24']
    ## 1番目のEthernetアダプタを natnetwork に設定する
    #vb.customize ['modifyvm', :id, '--nic1', 'natnetwork']
    #vb.customize ['modifyvm', :id, '--nat-network1', 'fake_inet']
  end

  # boxes at https://vagrantcloud.com/search.
  #config.vm.box = "debian/buster64"
  #config.vm.box = "debian/bullseye64"

  # ツール類のインストール
  provision_for_tools = <<-SHELL
    set -e
    apt-get install -y screen socat tcpdump vim
    sudo -u vagrant sh -c 'wget -q -O - https://gist.githubusercontent.com/miminashi/1d7890a1a5e8d5b18e0c1a9c5e4fff2e/raw | sh -s'
  SHELL

  # tincノードのセットアップ
  provision_for_tinc_node = <<-SHELL
    # このスクリプト内でエラーがでたときは終了する
    set -e
    # スクリプトを配置する
    chmod +x /tmp/bin/*
    cp /tmp/bin/* /usr/local/sbin
    chmod +x /tmp/setup_gateway.sh
    # ノードのセットアップをする
    /tmp/setup_gateway.sh %s %s
  SHELL

  # ルートノードの想定のVM
  config.vm.define "fakeroot" do |host|
    host.vm.box = "debian/buster64"
    host.vm.hostname = "fakeroot"
    host.vm.network "private_network", ip: "172.16.38.1", netmask: "24", virtualbox__intnet: "fake_inet"  # インターネットのかわり
    host.vm.provision "file", source: "./setup_gateway.sh", destination: "/tmp/"
    host.vm.provision "file", source: "./bin", destination: "/tmp/"
    host.vm.provision "shell", inline: provision_for_tools
    host.vm.provision "shell", inline: provision_for_tinc_node % [host.vm.hostname, "10.50.255.1"]
  end

  # ブロードバンドルーター
  config.vm.define "bbrt" do |vyos|
    vyos.vm.box = "vyos/current"
    vyos.vm.hostname = "bbrt"
    #vyos.vm.network "private_network", ip: "172.16.38.2", netmask: "24", virtualbox__intnet: "fake_inet"  # インターネットのかわり
    #vyos.vm.network "private_network", ip: "192.168.111.1", netmask: "24", virtualbox__intnet: "fake_lan" # LANのかわり
    # vagrant-vyosの実装がいいかげんで 255.255.255.0 の形式じゃないとサブネットマスクを受け付けてくれない
    #   https://github.com/higebu/vagrant-vyos/blob/master/lib/vagrant-vyos/cap/configure_networks.rb#L22
    #vyos.vm.network "private_network", ip: "172.16.38.2", netmask: "255.255.255.0", virtualbox__intnet: "fake_inet"  # インターネットのかわり
    #vyos.vm.network "private_network", type: "dhcp", virtualbox__intnet: "fake_inet"  # インターネットのかわり
    #vyos.vm.network "private_network", ip: "192.168.111.1", netmask: "255.255.255.0", virtualbox__intnet: "fake_lan" # LANのかわり
  end

  # 各参加者のLANに設置されるまちかどネットワークゲートウェイの想定のVM
  config.vm.define "gateway" do |host|
    host.vm.box = "debian/buster64"
    host.vm.hostname = "gateway"
    host.vm.network "private_network", ip: "172.16.38.2", netmask: "24", virtualbox__intnet: "fake_inet"  # インターネットのかわり
    host.vm.network "private_network", ip: "192.168.111.2", netmask: "24", virtualbox__intnet: "fake_lan" # LANのかわり
    host.vm.provision "file", source: "./setup_gateway.sh", destination: "/tmp/"
    host.vm.provision "file", source: "./bin", destination: "/tmp/"
    host.vm.provision "shell", inline: provision_for_tools
    host.vm.provision "shell", inline: provision_for_tinc_node % [host.vm.hostname, "10.50.255.2"]
  end

  # LAN側の端末の想定のVM
  config.vm.define "client" do |host|
    host.vm.box = "debian/buster64"
    host.vm.hostname = "client"
    host.vm.network "private_network", ip: "192.168.111.3", netmask: "24", virtualbox__intnet: "fake_lan" # LANのかわり
    host.vm.provision "shell", inline: provision_for_tools
    host.vm.provision "shell", inline: <<-SHELL
      # まちかどネットワークへの経路を追加する
      ip route add 10.50.0.0/16 via 192.168.111.2
    SHELL
  end
end
